[package]
name = "manga"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
eyre = "0.6.12"