[package]
name = "manga"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
eyre = "0.6.12"
image = "0.25.5"
futures = "0.3.31"